### ISSUE TITLE
GitHub ActionsによるCI/CDパイプラインの構築

### ISSUE THREAD

**Issue by ar4rpon** [ar4rpon/minelibrary#89]
## 概要
GitHub Actionsを使用して自動テスト実行とデプロイメントのパイプラインを構築します。

## 目的
- コード品質の自動チェック
- テストの自動実行による品質保証
- 本番環境への安全なデプロイメント
- 開発効率の向上

### 1. Pull Request時のチェック（.github/workflows/pr-check.yml）
- [ ] PHPStan/Larastanによる静的解析
- [ ] PHP CS Fixerによるコードスタイルチェック
- [ ] Pestによるユニット/フィーチャーテスト実行
- [ ] ESLintによるJavaScriptコードチェック
- [ ] npm run buildの成功確認
- [ ] テストカバレッジレポートの生成

### 2. mainブランチへのマージ時（.github/workflows/main-deploy.yml）
- [ ] 本番環境へのデプロイメント
- [ ] データベースマイグレーションの実行
- [ ] アセットのビルドとデプロイ
- [ ] キャッシュのクリア
- [ ] デプロイ完了通知

### 3. 定期実行ワークフロー（.github/workflows/scheduled.yml）
- [ ] 依存関係の脆弱性チェック（週次）
- [ ] パフォーマンステストの実行（日次）
- [ ] バックアップの実行（日次）

### PR Check ワークフロー
```yaml
name: PR Check
on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
    steps:
      - Checkout
      - Setup PHP
      - Install dependencies
      - Run tests
      - Upload coverage
```

### セキュリティ設定
- [ ] GitHub Secretsの設定
  - [ ] DATABASE_URL
  - [ ] APP_KEY
  - [ ] デプロイ用認証情報
- [ ] 環境変数の適切な管理
- [ ] デプロイキーの設定

### 通知設定
- [ ] テスト失敗時の通知
- [ ] デプロイ成功/失敗の通知
- [ ] Slackインテグレーション（オプション）

### Phase 1: 基本的なテスト実行（1週目）
- PR時のPHPテスト実行
- コードスタイルチェック

### Phase 2: 品質チェックの追加（2週目）
- 静的解析の追加
- カバレッジレポート

### Phase 3: デプロイメント自動化（3週目）
- mainブランチへのデプロイ
- 環境変数の設定

### Phase 4: 高度な機能（4週目）
- 定期実行ジョブ
- パフォーマンステスト

## 成功基準
- すべてのPRで自動テストが実行される
- mainブランチへのマージで自動デプロイが行われる
- テスト失敗時にマージがブロックされる
- デプロイの成功率95%以上

## 必要なツール・サービス
- GitHub Actions（無料枠で十分）
- Codecov or Coveralls（カバレッジ可視化）
- デプロイ先のサーバー情報

## 関連イシュー
- #87 テスト環境の基盤セットアップ
- #88 Laravel（バックエンド）テストの実装計画

## 見積もり工数
約1週間（基本的なCI/CD構築）
